[package]
name = "infinitable"
version = "1.0.0"
authors = ["Philip Chung <philipchung1995@yahoo.com>"]
description = "Infinity for types without infinite values"
repository = "https://github.com/philipchungtech/rust-infinitable"
readme = "README.md"
license = "BSD-2-Clause"

[dependencies]
